maliput/maliput_malidrive

- src/maliput_malidrive/test_utilities/road_geometry_configuration_for_xodrs.cc
- src/utility/resources.cc
- src/utility/resources.h
- test/CMakeLists.txt
- test/regression/CMakeLists.txt
- test/regression/base/road_geometry_test.cc
- test/regression/builder/builder_tools_test.cc
- test/regression/builder/phase_provider_builder_test.cc
- test/regression/builder/road_geometry_builder_test.cc
- test/regression/builder/road_network_builder_test.cc
- test/regression/builder/road_rulebook_builder_test.cc
- test/regression/builder/rule_registry_builder_test.cc
- test/regression/loader/loader_test.cc
- test/regression/plugin/road_network_plugin_test.cc
- test/regression/utility/CMakeLists.txt
- test/regression/utility/resources_test.cc
- test/regression/xodr/db_manager_test.cc
Proposes a solution for https://github.com/maliput/maliput_malidrive/pull/218#issuecomment-1151657707
Signed-off-by: Franco Cipollone <franco.c@ekumenlabs.com>
> Uses compile definitions to avoid having to source install when running the tests.

- package.xml
Part of https://github.com/maliput/maliput_infrastructure/issues/273
Related to https://github.com/maliput/maliput_infrastructure/issues/269
Signed-off-by: Franco Cipollone <franco.c@ekumenlabs.com>
> Use <doc_depend> for ament_cmake_doxygen dependency

- src/maliput_malidrive/base/lane.cc
- src/maliput_malidrive/base/lane.h
- test/regression/base/lane_test.cc
Related to https://github.com/maliput/maliput/issues/496
Matches with https://github.com/maliput/maliput/pull/521
action-ros-ci-repos-override: https://gist.githubusercontent.com/francocipollone/b218a7671b9bb6b6be2c22ac19f85793/raw/8c1e3852f99a5ea730b12be37ac6c6205cf67a2a/maliput_malidrive.repos
> Matches with changes in Maliput: Lane::ToLanePosition.

- src/maliput_malidrive/builder/phase_provider_builder.cc
Depends on https://github.com/maliput/maliput/pull/530
Remove custom implementation as default populated ManualPhaseProvider is provided at https://github.com/maliput/maliput/pull/530
action-ros-ci-repos-override: https://gist.githubusercontent.com/francocipollone/b218a7671b9bb6b6be2c22ac19f85793/raw/a6e2832ee69e953cdf9cf5391a0a000dc569653e/maliput_malidrive.repos
> Uses default ManualPhaseProvider implementation.

- CMakeLists.txt
- package.xml
- This dependency was missing, causing CI to fail.
- Recently the dependency was removed from maliput package: https://github.com/maliput/maliput/pull/559 
- Maybe malidrive was getting the implict dependency from there and that's why it was working.
> Adds missing gflags dependency to package.

- .bazelrc
- .devcontainer/README.md
- .github/workflows/build.yml
- .gitignore
- BUILD.bazel
- MODULE.bazel
- WORKSPACE.bazel
- resources/BUILD.bazel
- test/CMakeLists.txt
Bazel module. 
[1] It will take some time to get `yaml-cpp`, `tinyxml` and `maliput` into the BCR itself.
No tests yet, also no idea how to get the plugin framework working with bazel. These will come in followup PR's.
With #235, load the devcontainer and `bazel build //...`
See also the CI result: https://github.com/maliput/maliput_malidrive/actions/runs/6239555329/job/16937711920?pr=236
> Bazel module

- CMakeLists.txt
- MODULE.bazel
- package.xml
- test/regression/xodr/db_manager_test.cc
- test/regression/xodr/parser_test.cc
- test/regression/xodr/xodr_extract_test.cc
Closes #234 
- Tests where fmt was used was replaced by custom code.
- fmt dependency was removed from maliput_malidrive.
> Removes fmt dependency

- .bazelrc
- BUILD.bazel
- MODULE.bazel
- src/maliput_malidrive/xodr/CMakeLists.txt
- src/plugin/CMakeLists.txt
Just watch the CI pre-merge checks. No other functionality changes.
> Decompose bazel superlibrary

- .github/workflows/wheel_generation.yml
- README.md
- Sets wheel generation workflow to run once a week.
- Adds badge status in the README file.
> Adds periodic wheel generation.(once a week)

- bazel/variables.bzl
Adds -O2 flag to bazel build to reduce execution time of tests.
See https://github.com/maliput/maliput_malidrive/pull/252#issuecomment-1818816657 for an example of the failures we face.
> Adds -O2 flag to bazel build.

- .github/workflows/wheel_generation.yml
Follow up to https://github.com/maliput/maliput_infrastructure/pull/316
The wheel generation workflow was not switching branches based on the naming scheme. Doing it here so it gets fixed.
> Adds try_vcs_checkout to wheel_generation workflow.

- .devcontainer/bazel-zen/Dockerfile
Edits the docker image for bazel usage to include pip and vcstool. That will allow https://github.com/maliput/maliput_malidrive/pull/253 to pull a docker image that contains vcs and avoid installing it each time.
> Adds vcstool and pip to bazel-zen docker image.

- src/maliput_malidrive/road_curve/CMakeLists.txt
- src/maliput_malidrive/road_curve/road_curve_offset.cc
- src/maliput_malidrive/road_curve/road_curve_offset.h
Pairs with https://github.com/maliput/maliput/pull/603
Replaces direct use of drake / eigen types by new classes  in maliput.
Via unit tests.
action-ros-ci-repos-override: https://gist.githubusercontent.com/francocipollone/b218a7671b9bb6b6be2c22ac19f85793/raw/734e35d0727e61f3f345b448fab0969ec21f5880/maliput_malidrive.repos
> Replaces the implementation to avoid using explicit drake imported types

- .github/workflows/build.yml
- .github/workflows/sanitizers.yml
- .github/workflows/scan_build.yml
Pairs with https://github.com/maliput/maliput_infrastructure/pull/317
Updates setup-ros to use v0.6 to avoid erros with empy.
> Updates ros-tooling version to avoid error with dependency.

- src/maliput_malidrive/xodr/parser.cc
- test/regression/xodr/parser_test.cc
Goes on top of https://github.com/maliput/maliput_malidrive/pull/261
Related to #260 
- Parses Spiral Geometries
After building and sourcing.
```
xodr_query src/maliput_malidrive/resources/SpiralRoad.xodr GetGeometries 1
```
> Enables spiral geometries parsing.

- src/maliput_malidrive/xodr/geometry.cc
- src/maliput_malidrive/xodr/geometry.h
- src/maliput_malidrive/xodr/parser.cc
- test/regression/xodr/geometry_test.cc
- test/regression/xodr/parser_test.cc
Related to #260 
From OpenDRIVE Format Specification 1.5: 
```
This record describes a spiral as part of the road’s reference line. For this type of spiral, the curvature
change between start and end of the element is linear.
In order to provide consistency between spiral evaluations of various implementations, users are
highly recommended to use identical algorithms, or, at least, algorithms with reasonable accuracy
within the applicable range (i.e. curvature, length of spiral etc.).
The theory of clothoids is described (for example) at
http://en.wikipedia.org/wiki/Euler_spiral
A library for computing clothoids can be downloaded at
http://www.opendrive.org/downloads/spiral.zip
```
After building and sourcing.
```
xodr_query src/maliput_malidrive/resources/SpiralRoad.xodr GetGeometries 1 …
```
> Adds spiral geometry parsing capabilities

- .bazelrc
- .bcr/config.yml
- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/release.yaml
- .github/workflows/sanitizers.yml
- .github/workflows/scan_build.yml
- MODULE.bazel
Migrate to the BCR (for both fetching dependencies and publishing of this package)
* Points bazel at the REAL BCR, not our fork
* CI automation for cutting releases and PR'ing the BCR
* Updates the dependency on maliput to that found on the BCR
* (other) Name consistency for CI workflows
> [infra] use the REAL bazel central registry

- BUILD.bazel
- MODULE.bazel
- src/applications/CMakeLists.txt
- src/applications/xodr_extract.cc
- src/applications/xodr_query.cc
- src/applications/xodr_to_obj.cc
Adds a command line utility for dumping .obj/.mtl files from an xodr.
Also:
* Bugfixes the return values of all applications to 0 on success
* Adds an xodr that is currently unsupported (spiral geometries) <- I was trying to get a .obj of this road network
Not fancy, but has the basics for getting a .obj file.
```
bazel run //:xodr_to_obj -- --xodr-file=${PWD}/resources/Town07.xodr --out-dir=${PWD}
```
> [applications] xodr_to_obj

- CHANGELOG.rst
- CMakeLists.txt
- MODULE.bazel
- package.xml
> Release 0.2.1.

- CHANGELOG.rst
- CMakeLists.txt
- MODULE.bazel
- package.xml
Prepare for release 0.3.0
Depends on:
- #279
- https://github.com/maliput/maliput/pull/630 and the posterior bazel release.
N/A
> Prepare for release 0.3.0

- MODULE.bazel
Point to latest maliput version in BCR. Related to https://github.com/maliput/maliput/pull/641
> Bazel: Bumps maliput to 1.3.1.

- CMakeLists.txt
- resources/ArcLaneRolled.xodr
- resources/ArcLaneRolledAndOffset.xodr
- src/maliput_malidrive/base/lane.h
- src/maliput_malidrive/base/road_geometry.cc
- src/maliput_malidrive/base/road_geometry.h
- src/maliput_malidrive/road_curve/road_curve.h
- test/regression/base/road_geometry_test.cc
> Provide some useful conversions for OpenScenario users

- .bcr/presubmit.yml
- BUILD.bazel
- Removes unnecessary library that bazel 8.x was complaining about due to unresolved regex 
- Adds 8.x to bcr's presubmit
> Support to bazel 8.x.

- src/maliput_malidrive/base/road_geometry.cc
- src/maliput_malidrive/base/road_geometry.h
- test/regression/base/road_geometry_test.cc
> Useful conversions from Maliput to OpenScenario Position types.

- CMakeLists.txt
- resources/SingleRoadSDirectionChange.xodr
- src/maliput_malidrive/base/road_geometry.cc
- src/maliput_malidrive/base/road_geometry.h
- test/regression/base/road_geometry_test.cc
- Provides conversion from OpenScenario RelativeRoadPosition to Maliput via the `BackendCustomCommand` API.
```cpp
// - OpenScenarioRelativeRoadPositionToMaliputRoadPosition
//   - Converts an OpenScenario RelativeRoadPosition to a maliput RoadPosition.
//   - In/Out:
//     - Input: "<xodr_road_id>,<xodr_s>,<xodr_t>,<ds>,<dt>"
//     - Output: "<lane_id>,<s>,<r>,<h>"
//   - See
//   https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/RelativeRoadPosition.html
```
> Provides OpenScenarioRelativeRoadPositionToMaliputRoadPosition conversion method

- src/maliput_malidrive/base/road_geometry.cc
- src/maliput_malidrive/base/road_geometry.h
- test/regression/base/road_geometry_test.cc
* Provides conversion from OpenScenario RelativeLanePosition to Maliput via the `BackendCustomCommand` API.
* Two different commands are added:
* `WithDs`: `s` coordinate offset through the road's reference line.
* `WithDsLane`: `s` coordinate offset through the lane's center line.
```
// - OpenScenarioRelativeLanePositionWithDsToMaliputRoadPosition
//   - Converts an OpenScenario RelativeLanePosition to a maliput RoadPosition.
//   - In/Out:
//     - Input: "<xodr_road_id>,<xodr_lane_id>,<xodr_s>,<d_lane>,<xodr_ds>,<offset>"
//     - Output: "<lane_id>,<s>,<r>,<h>"
//   - See
//   https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/RelativeLanePosition.html
//
// - OpenScenarioRelativeLanePositionWithDsLaneToMaliputRoadPosition …
```
> Provides OpenScenarioRelativeLanePositionToMaliputRoadPosition conversion method

- src/maliput_malidrive/base/road_geometry.cc
- src/maliput_malidrive/base/road_geometry.h
- test/regression/base/road_geometry_test.cc
```
// - GetRoadOrientationAtOpenScenarioRoadPosition
//   - Obtains the road orientation at a OpenScenario RoadPosition.
//   - In/Out:
//     - Input: "<xodr_road_id>,<xodr_s>,<xodr_t>"
//     - Output: "<roll>,<pitch>,<yaw>"
//   - See
//   https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/latest/generated/content/RoadPosition.html
```
* Adds a custom command to obtain the `roll`, `pitch` and `yaw` angles at a RoadPosition.
* Added tests.
> Provide method to obtain the road orientation from a OS RoadPosition.

- MODULE.bazel
- Depends on https://github.com/maliput/maliput/pull/647 and its BCR release
- Depends on https://github.com/bazelbuild/bazel-central-registry/pull/4388
> Bazel: Bump to use latest maliput and eigen release.

- include/maliput_malidrive/builder/params.h
- src/maliput_malidrive/builder/road_curve_factory.cc
- src/maliput_malidrive/builder/road_curve_factory.h
- src/maliput_malidrive/builder/road_geometry_builder.cc
- test/regression/builder/road_curve_factory_test.cc
Closes #302
This PR allows reference lane offset discontinuities by leaving in the user hands that the resulting roads form a contiguous surface.
Additionally, Maliput now throws an exception if the `standard_strictness_policy` is set to strict, and the reference lane offset is not contiguous.
> Allow offset discontinuities when allowing semantic errors in XODRs.

- CHANGELOG.rst
- CMakeLists.txt
- MODULE.bazel
- package.xml
* Depends on #305  and #306 
Prepare for release 0.5.0.
Point to maliput 1.4.2.
> Prepare for maliput_malidrive release 0.5.0

- CHANGELOG.rst
- CMakeLists.txt
- MODULE.bazel
- package.xml
Point to `maliput` `1.5.0` version.
Prepare for `maliput_malidrive` `0.6.0` release.
> Prepare for maliput_malidrive minor release.

- src/maliput_malidrive/builder/road_curve_factory.cc
- src/maliput_malidrive/builder/road_geometry_builder.cc
- src/maliput_malidrive/road_curve/piecewise_function.cc
- src/maliput_malidrive/road_curve/road_curve_offset.cc
- src/maliput_malidrive/xodr/db_manager.cc
- src/maliput_malidrive/xodr/parser.cc
All warning messages are now part of `DEBUG` log level. This is an effort to not spam the user with a lot of noisy messages when running maliput with a `permissive` strictness level.
Running the following query:
```
maliput_to_obj --maliput_backend=malidrive --xodr_file_path=src/maliput_malidrive/resources/GapInLaneWidthDrivableLane.xodr  --linear_tolerance=0.05 --dirpath=src/maliput_malidrive/obj/ --file_name_root="GapIn
LaneWidth" --draw_elevation_bounds=False --standard_strictness_policy=permissive --log_level=info
```
used to output:
```
[INFO] Loading road network using malidrive backend implementation...
[WARNING] Error when constructing piecewise function. Endpoint distance is <1.200000> which is greater than tolerance: 0.050000>.
[INFO] RoadNetwork loaded successfully.
[INFO] OBJ …
```
> Change all warn level logging to debug level.

- include/maliput_malidrive/builder/params.h
- src/maliput_malidrive/base/lane.cc
- src/maliput_malidrive/base/lane.h
- src/maliput_malidrive/builder/road_geometry_builder.cc
- src/maliput_malidrive/builder/road_geometry_configuration.cc
- src/maliput_malidrive/builder/road_geometry_configuration.h
- src/maliput_malidrive/road_curve/road_curve_offset.cc
- src/maliput_malidrive/road_curve/road_curve_offset.h
- test/regression/base/lane_test.cc
- test/regression/builder/road_geometry_configuration_test.cc
- test/regression/road_curve/road_curve_offset_test.cc
- Add builder param to tune integrator accuracy: `integrator_accuracy_multiplier`
> Add builder param to tune integrator accuracy.

- src/maliput_malidrive/base/road_geometry.cc
- src/maliput_malidrive/base/road_geometry.h
- test/regression/base/road_geometry_test.cc
- xodr lane position wasn't correctly converted to a maliput lane.
- tests were added to convert these cases.
> Bug fix for OpenScenarioLanePos to maliput lane conversion.

- src/maliput_malidrive/xodr/parser.cc
- test/regression/xodr/parser_test.cc
> xodr parser: Log instead of throw in some center lane rule checks.

- src/maliput_malidrive/xodr/lane.cc
- src/maliput_malidrive/xodr/lane.h
- src/maliput_malidrive/xodr/parser.cc
- test/regression/xodr/lane_test.cc
- test/regression/xodr/parser_test.cc
Support to parse XODR Lane attributes added in OpenDRIVE version 1.8 such as:
*  Advisory
* Direction
* DynamicLaneDirection
* DynamicLaneType
* RoadWorks
See for more info: https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/11_lanes/11_02_lane_groups.html
> Parse Lane attributes added in OpenDRIVE 1.8

- resources/StraightRoadMultipleLaneDirections.xodr
- src/maliput_malidrive/builder/builder_tools.cc
- src/maliput_malidrive/builder/builder_tools.h
- src/maliput_malidrive/builder/direction_usage_builder.cc
- src/maliput_malidrive/builder/road_rulebook_builder.cc
- src/maliput_malidrive/test_utilities/road_geometry_configuration_for_xodrs.cc
- src/maliput_malidrive/xodr/README.md
- src/maliput_malidrive/xodr/lane.h
- test/regression/builder/builder_tools_test.cc
- test/regression/builder/road_network_builder_test.cc
- test/regression/builder/rule_registry_builder_test.cc
Closes #316 
* **WARNING**: This PR modifies current behavior by mapping right lanes direction to `WithS` (RHT) when road direction rule is omitted, instead of leaving `Undefined`.
* Parse XODR road rule to determine if traffic follows `WithS` on the right or left lane.
* Parse XODR lane direction to override road rule.
* Each lane can set if it follows the standard or reversed direction stated by the road rule, or even be bidirectional.
* See [OpenDRIVE Lane direction](https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/16_annexes/enumerations/map_uml_enumerations.html#top-EAID_BDEEA32B_3F22_4f2c_A327_04437D41CC3D) for more details.
* Get direction rules based on the following precedence:
* 1. `userData` XODR node present within …
> Use road::rule XODR attribute to convert to a traffic direction rule.

- src/maliput_malidrive/base/road_geometry.cc
- src/maliput_malidrive/base/road_geometry.h
- test/regression/base/road_geometry_test.cc
Closes #325 
* Removes check for r-coordinate bounds when converting OpenScenario `LanePosition`s into maliput `RoadPosition`s.
* Update docs.
> Allow OS Lane position conversions to off road r-coordinates.

- src/maliput_malidrive/base/lane.cc
- src/maliput_malidrive/road_curve/arc_ground_curve.h
- src/maliput_malidrive/road_curve/cubic_polynomial.h
- src/maliput_malidrive/road_curve/lane_offset.cc
- src/maliput_malidrive/road_curve/lane_offset.h
- src/maliput_malidrive/road_curve/line_ground_curve.h
- src/maliput_malidrive/road_curve/piecewise_function.cc
- src/maliput_malidrive/road_curve/piecewise_ground_curve.cc
- src/maliput_malidrive/road_curve/scaled_domain_function.h
- src/maliput_malidrive/road_curve/spiral_ground_curve.cc
- src/maliput_malidrive/road_curve/spiral_ground_curve.h
- test/regression/builder/road_curve_factory_test.cc
- test/regression/road_curve/arc_ground_curve_test.cc
- test/regression/road_curve/cubic_polynomial_test.cc
- test/regression/road_curve/lane_offset_test.cc
- test/regression/road_curve/line_ground_curve_test.cc
- test/regression/road_curve/spiral_ground_curve_test.cc
Relates to https://github.com/maliput/maliput/issues/666
`RangeValidator` now throws user defined error types, instead of always `assertion_error`.
> Add custom error types to RangeValidator instances.

- .github/workflows/build.yml
- .github/workflows/build_macos.yaml
- src/applications/xodr_query.cc
- src/maliput_malidrive/builder/builder_tools.cc
- src/maliput_malidrive/builder/builder_tools.h
- src/maliput_malidrive/xodr/db_manager.cc
- src/maliput_malidrive/xodr/db_manager.h
- src/maliput_malidrive/xodr/junction.h
- src/maliput_malidrive/xodr/parser.cc
- test/regression/builder/road_geometry_builder_test.cc
- test/regression/xodr/db_manager_test.cc
- This was causing the default branch lane end selection not to be robust.
- It was noticed after compiling in clang compiler as well.
> Move junction collection from unordered_map to map

- MODULE.bazel
- test/regression/base/road_geometry_test.cc
* Test with input position in the middle of the road with a small radius returns one position in that road.
* Test with big radius returns all lanes.
* Test with input position between 2 lanes in the same segment returns both lanes.
* Test with input position at the end of road returns all branching roads (see pic below).
* Points to `maliput 1.8.1`.
> Add tests for KDTree strategy FindRoadPositions with actual XODR.
