maliput/maliput_malidrive

include/maliput_malidrive/common/macros.h
src/applications/xodr_extract.cc
src/applications/xodr_query.cc
src/applications/xodr_validate.cc
src/maliput_malidrive/base/lane.cc
src/maliput_malidrive/builder/builder_tools.cc
src/maliput_malidrive/builder/direction_usage_builder.cc
src/maliput_malidrive/builder/road_curve_factory.cc
src/maliput_malidrive/builder/road_geometry_builder.cc
src/maliput_malidrive/builder/road_network_builder.cc
src/maliput_malidrive/builder/road_rulebook_builder.cc
src/maliput_malidrive/builder/road_rulebook_builder_old_rules.cc
src/maliput_malidrive/builder/rule_registry_builder.cc
src/maliput_malidrive/builder/speed_limit_builder.cc
src/maliput_malidrive/road_curve/piecewise_ground_curve.cc
src/maliput_malidrive/road_curve/road_curve_offset.cc
src/maliput_malidrive/xodr/db_manager.cc
src/maliput_malidrive/xodr/parser.cc
src/maliput_malidrive/xodr/parser.h
src/maliput_malidrive/xodr/xodr_extract.cc
test/regression/xodr/parser_test.cc

Matches with https://github.com/maliput/maliput/pull/568
What the title says
action-ros-ci-repos-override: https://gist.githubusercontent.com/francocipollone/b218a7671b9bb6b6be2c22ac19f85793/raw/501a2f86f08d3d60cfa3d7af1cdc864667479bb2/maliput_malidrive.repos

Matches with change in logger format.

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

Release v0.2.0

---

BUILD.bazel

[bazel] Guarantee shared library creation for the plugin

---

src/maliput_malidrive/xodr/README.md

Closes #278
Changes the documentation status
N/A

Flags spiral support.

---

.github/workflows/build.yml
.github/workflows/containers.yml
.github/workflows/release.yaml
.github/workflows/sanitizers.yml
.github/workflows/scan_build.yml
.github/workflows/wheel_generation.yml

Part of  https://github.com/maliput/maliput_infrastructure/issues/319
Update github action versions.
N/A

Update github action versions.

---

.bcr/presubmit.yml

https://github.com/bazelbuild/bazel-central-registry/pull/3032#discussion_r1819095940

Minor changes to presubmit.yml file.

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

Prepare for 0.3.1 release.

---

src/maliput_malidrive/base/road_geometry.cc
src/maliput_malidrive/base/road_geometry.h
test/regression/base/road_geometry_test.cc

Related to https://github.com/maliput/maliput/pull/643
ditto

Implements DoBackendCustomCommand method.

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

ditto
:exclamation: This need https://github.com/bazelbuild/bazel-central-registry/pull/3967 to be merged to pass CI
After it is merged I will push the tag 0.4.0

Prepare for release 0.4.0

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

Prepare for release 0.4.1

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

Prepare for release 0.4.2

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

Prepare for release 0.4.3

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

- Depends on #303 
Prepare for release 0.4.4

Prepare for 0.4.4 release

---

include/maliput_malidrive/builder/params.h
include/maliput_malidrive/constants.h
resources/GapInLaneWidthDrivableLane.xodr
src/maliput_malidrive/builder/road_curve_factory.cc
src/maliput_malidrive/builder/road_curve_factory.h
src/maliput_malidrive/builder/road_geometry_builder.cc
src/maliput_malidrive/road_curve/piecewise_function.cc
src/maliput_malidrive/test_utilities/road_geometry_configuration_for_xodrs.cc
test/regression/builder/road_curve_factory_test.cc
test/regression/builder/road_geometry_builder_test.cc
test/regression/builder/road_network_builder_test.cc

Adapt driveable lane's widths so they are C1 continuous.

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

Prepare for 0.7.1 release.

---

src/maliput_malidrive/xodr/CMakeLists.txt
src/maliput_malidrive/xodr/README.md
src/maliput_malidrive/xodr/geo_reference.cc
src/maliput_malidrive/xodr/geo_reference.h
src/maliput_malidrive/xodr/header.cc
src/maliput_malidrive/xodr/header.h
src/maliput_malidrive/xodr/offset.cc
src/maliput_malidrive/xodr/offset.h
src/maliput_malidrive/xodr/parser.cc
test/regression/xodr/CMakeLists.txt
test/regression/xodr/geo_reference_test.cc
test/regression/xodr/header_test.cc
test/regression/xodr/offset_test.cc
test/regression/xodr/parser_test.cc

Parse `geoReference` and `offset` XODR elements.

---

src/maliput_malidrive/base/road_geometry.cc
src/maliput_malidrive/base/road_geometry.h
test/regression/base/road_geometry_test.cc

Implement GeoReferenceInfo API

---

BUILD.bazel

Bazel: Road network plugin's deps linked statically.

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

* Points to maliput 1.7.1 version.
* Prepare for 0.10.1 release.

Prepare for release 0.10.1

---

CHANGELOG.rst
CMakeLists.txt
MODULE.bazel
package.xml

Prepare 0.11.0 release.
